version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
        MONGO_HOST: "172.20.10.13"
        MONGO_PORT: "27017"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /Users/diasc/code/docker/local/markersapp/data/mongodb/db:/Users/diasc/code/docker/local/markersapp/data/db
    ports:
      - "27017:27017"
    environment:
      - "contraint:node==172.20.10.13"
